DROP TABLE IF EXISTS CLIENT CASCADE;
CREATE TABLE CLIENT (
  ID        SERIAL,
  FIRSTNAME VARCHAR(40) NOT NULL,
  LASTNAME  VARCHAR(40) NOT NULL,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS PRODUCT CASCADE;
CREATE TYPE currency AS ENUM ('UAH', 'USD', 'EUR');
CREATE TABLE PRODUCT (
  ID       SERIAL,
  NAME     VARCHAR(50) NOT NULL,
  PRICE    FLOAT       NOT NULL,
  CURRENCY currency    NOT NULL,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS (
  ID         SERIAL,
  PRODUCT_ID INT REFERENCES PRODUCT (ID),
  QUANTITY   INT       NOT NULL,
  CLIENT_ID  INT REFERENCES CLIENT (ID),
  DATEBUY    TIMESTAMP NOT NULL,
  PRIMARY KEY (ID)
);